All seed types

In [3]:
import pandas as pd
from miRBench.dataset import get_dataset_df 

df1=get_dataset_df('AGO2_CLASH_Hejret2023', split="test")[['gene', 'noncodingRNA', 'label']]
df2=get_dataset_df('AGO2_eCLIP_Klimentova2022', split="test")[['gene', 'noncodingRNA', 'label']]
df3=get_dataset_df("AGO2_eCLIP_Manakov2022", split='test')[['gene', 'noncodingRNA', 'label']]
df4=get_dataset_df("AGO2_eCLIP_Manakov2022", split='leftout')[['gene', 'noncodingRNA', 'label']]
datasets= {"AGO2_CLASH_Hejret2023": df1,
    "AGO2_eCLIP_Klimentova2022": df2,
    "AGO2_eCLIP_Manakov2022_test":df3,
    "AGO2_eCLIP_Manakov2022_leftout":df4
    }

def get_seed6mer(noncodingRNA):
    return [noncodingRNA[1:7],noncodingRNA[2:8],'A'+noncodingRNA[1:6]]

def get_seed7mer(noncodingRNA) :
    return [noncodingRNA[1:8],'A'+noncodingRNA[1:7]]

def get_seed8mer(noncodingRNA):
    return ['A'+noncodingRNA[1:8]]

for name, df in datasets.items():
    df['seed6mer (1:7)(2:8)(A+1:6)']=df['noncodingRNA'].apply(get_seed6mer)
    print (f'----{name}----')
    display(df[['noncodingRNA','seed6mer (1:7)(2:8)(A+1:6)']].head())

for name, df in datasets.items():
    df['seed7mer (1:8)(A+1:7)']=df['noncodingRNA'].apply(get_seed7mer)
    print (f'----{name}----')
    display(df[['noncodingRNA','seed7mer (1:8)(A+1:7)']].head())

for name, df in datasets.items():
    df['seed8mer (A+1:8)']=df['noncodingRNA'].apply(get_seed8mer)
    print (f'----{name}----')
    display(df[['noncodingRNA', 'seed8mer (A+1:8)']].head())

df1.to_csv("AGO2_CLASH_Hejret2023.csv", index=False)
df2.to_csv("AGO2_eCLIP_Klimentova2022.csv", index=False)
df3.to_csv("AGO2_eCLIP_Manakov2022_test.csv", index=False)
df4.to_csv("AGO2_eCLIP_Manakov2022_leftout.csv", index=False)

Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_CLASH_Hejret2023\test\dataset.tsv
Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_eCLIP_Klimentova2022\test\dataset.tsv
Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_eCLIP_Manakov2022\test\dataset.tsv
Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_eCLIP_Manakov2022\leftout\dataset.tsv
----AGO2_CLASH_Hejret2023----

                noncodingRNA seed6mer (1:7)(2:8)(A+1:6)
0    AAAGCAAATGTTGGGTGAACGGC   [AAGCAA, AGCAAA, AAAGCA]
1    AATAGCTCAGAATGTCAGTTCTG   [ATAGCT, TAGCTC, AATAGC]
2  AGAATTCTCTTATCCAACATCAACA   [GAATTC, AATTCT, AGAATT]
3     GCTAAGGAAGTCCTGTGCTCAG   [CTAAGG, TAAGGA, ACTAAG]
4   TGAAGCGCCTGTGCTCTGCCGAGA   [GAAGCG, AAGCGC, AGAAGC]

----AGO2_eCLIP_Klimentova2022----

              noncodingRNA seed6mer (1:7)(2:8)(A+1:6)
0  TAAGGTGCATCTAGTGCAGATAG   [AAGGTG, AGGTGC, AAAGGT]
1  TAAGGTGCATCTAGTGCAGATAG   [AAGGTG, AGGTGC, AAAGGT]
2  AAAAGTGCTTACAGTGCAGGTAG   [AAAGTG, AAGTGC, AAAAGT]
3  TAAGGTGCATCTAGTGCAGATAG   [AAGGTG, AGGTGC, AAAGGT]
4  TAAAGTGCTTATAGTGCAGGTAG   [AAAGTG, AAGTGC, AAAAGT]

----AGO2_eCLIP_Manakov2022_test----

              noncodingRNA seed6mer (1:7)(2:8)(A+1:6)
0  TAAAGTGCTTATAGTGCAGGTAG   [AAAGTG, AAGTGC, AAAAGT]
1  TAAGGTGCATCTAGTGCAGATAG   [AAGGTG, AGGTGC, AAAGGT]
2  CAAAGTGCTTACAGTGCAGGTAG   [AAAGTG, AAGTGC, AAAAGT]
3  ACTGCCCTAAGTGCTCCTTCTGG   [CTGCCC, TGCCCT, ACTGCC]
4    TAAAGTGCTGACAGTGCAGAT   [AAAGTG, AAGTGC, AAAAGT]

----AGO2_eCLIP_Manakov2022_leftout----

             noncodingRNA seed6mer (1:7)(2:8)(A+1:6)
0  AAGCTGCCAGTTGAAGAACTGT   [AGCTGC, GCTGCC, AAGCTG]
1  AAGCTGCCAGTTGAAGAACTGT   [AGCTGC, GCTGCC, AAGCTG]
2  AAGCTGCCAGTTGAAGAACTGT   [AGCTGC, GCTGCC, AAGCTG]
3  AAGCTGCCAGTTGAAGAACTGT   [AGCTGC, GCTGCC, AAGCTG]
4  AAGCTGCCAGTTGAAGAACTGT   [AGCTGC, GCTGCC, AAGCTG]

----AGO2_CLASH_Hejret2023----

                noncodingRNA seed7mer (1:8)(A+1:7)
0    AAAGCAAATGTTGGGTGAACGGC    [AAGCAAA, AAAGCAA]
1    AATAGCTCAGAATGTCAGTTCTG    [ATAGCTC, AATAGCT]
2  AGAATTCTCTTATCCAACATCAACA    [GAATTCT, AGAATTC]
3     GCTAAGGAAGTCCTGTGCTCAG    [CTAAGGA, ACTAAGG]
4   TGAAGCGCCTGTGCTCTGCCGAGA    [GAAGCGC, AGAAGCG]

----AGO2_eCLIP_Klimentova2022----

              noncodingRNA seed7mer (1:8)(A+1:7)
0  TAAGGTGCATCTAGTGCAGATAG    [AAGGTGC, AAAGGTG]
1  TAAGGTGCATCTAGTGCAGATAG    [AAGGTGC, AAAGGTG]
2  AAAAGTGCTTACAGTGCAGGTAG    [AAAGTGC, AAAAGTG]
3  TAAGGTGCATCTAGTGCAGATAG    [AAGGTGC, AAAGGTG]
4  TAAAGTGCTTATAGTGCAGGTAG    [AAAGTGC, AAAAGTG]

----AGO2_eCLIP_Manakov2022_test----

              noncodingRNA seed7mer (1:8)(A+1:7)
0  TAAAGTGCTTATAGTGCAGGTAG    [AAAGTGC, AAAAGTG]
1  TAAGGTGCATCTAGTGCAGATAG    [AAGGTGC, AAAGGTG]
2  CAAAGTGCTTACAGTGCAGGTAG    [AAAGTGC, AAAAGTG]
3  ACTGCCCTAAGTGCTCCTTCTGG    [CTGCCCT, ACTGCCC]
4    TAAAGTGCTGACAGTGCAGAT    [AAAGTGC, AAAAGTG]

----AGO2_eCLIP_Manakov2022_leftout----

             noncodingRNA seed7mer (1:8)(A+1:7)
0  AAGCTGCCAGTTGAAGAACTGT    [AGCTGCC, AAGCTGC]
1  AAGCTGCCAGTTGAAGAACTGT    [AGCTGCC, AAGCTGC]
2  AAGCTGCCAGTTGAAGAACTGT    [AGCTGCC, AAGCTGC]
3  AAGCTGCCAGTTGAAGAACTGT    [AGCTGCC, AAGCTGC]
4  AAGCTGCCAGTTGAAGAACTGT    [AGCTGCC, AAGCTGC]

----AGO2_CLASH_Hejret2023----

                noncodingRNA seed8mer (A+1:8)
0    AAAGCAAATGTTGGGTGAACGGC       [AAAGCAAA]
1    AATAGCTCAGAATGTCAGTTCTG       [AATAGCTC]
2  AGAATTCTCTTATCCAACATCAACA       [AGAATTCT]
3     GCTAAGGAAGTCCTGTGCTCAG       [ACTAAGGA]
4   TGAAGCGCCTGTGCTCTGCCGAGA       [AGAAGCGC]

----AGO2_eCLIP_Klimentova2022----

              noncodingRNA seed8mer (A+1:8)
0  TAAGGTGCATCTAGTGCAGATAG       [AAAGGTGC]
1  TAAGGTGCATCTAGTGCAGATAG       [AAAGGTGC]
2  AAAAGTGCTTACAGTGCAGGTAG       [AAAAGTGC]
3  TAAGGTGCATCTAGTGCAGATAG       [AAAGGTGC]
4  TAAAGTGCTTATAGTGCAGGTAG       [AAAAGTGC]

----AGO2_eCLIP_Manakov2022_test----

              noncodingRNA seed8mer (A+1:8)
0  TAAAGTGCTTATAGTGCAGGTAG       [AAAAGTGC]
1  TAAGGTGCATCTAGTGCAGATAG       [AAAGGTGC]
2  CAAAGTGCTTACAGTGCAGGTAG       [AAAAGTGC]
3  ACTGCCCTAAGTGCTCCTTCTGG       [ACTGCCCT]
4    TAAAGTGCTGACAGTGCAGAT       [AAAAGTGC]

----AGO2_eCLIP_Manakov2022_leftout----

             noncodingRNA seed8mer (A+1:8)
0  AAGCTGCCAGTTGAAGAACTGT       [AAGCTGCC]
1  AAGCTGCCAGTTGAAGAACTGT       [AAGCTGCC]
2  AAGCTGCCAGTTGAAGAACTGT       [AAGCTGCC]
3  AAGCTGCCAGTTGAAGAACTGT       [AAGCTGCC]
4  AAGCTGCCAGTTGAAGAACTGT       [AAGCTGCC]