In [1]:
from miRBench.dataset import list_datasets

list_datasets()

['AGO2_CLASH_Hejret2023',
 'AGO2_eCLIP_Klimentova2022']

['AGO2_CLASH_Hejret2023', 'AGO2_eCLIP_Klimentova2022']

In [2]:
from miRBench.dataset import get_dataset_df

dataset_name = "AGO2_CLASH_Hejret2023"
df = get_dataset_df(dataset_name, split="test")
df.head()

Downloading AGO2_CLASH_Hejret2023 dataset, split test into C:\Users\05vic\.miRBench\datasets\20540907\AGO2_CLASH_Hejret2023\test\dataset.tsv

,gene,noncodingRNA,noncodingRNA_name,noncodingRNA_fam,feature,label,chr,start,end,strand,Nunique,dominant_region,regions_present,read_start_in_sel_tx_1based,read_end_in_sel_tx_1based,gene_cluster_ID,gene_phyloP,gene_phastCons
0,GGAGTCTGGAGTCAAACCCAGAGCAGCTGCAGGCCATGAGGCACAT...,AAAGCAAATGTTGGGTGAACGGC,hsa-miR-10527-5p,unknown,exon,0,1,112694760,112694809,+,0,CDS,CDS,20016.0,20065.0,834,"[2.923, 0.02, 2.412, 1.039, 0.48, 2.867, 7.669...","[1.0, 0.943, 0.99, 0.99, 0.99, 1.0, 1.0, 1.0, ..."
1,CAGCTGTGTACAGCGCCATCTCTCTGCCTTCTGTTGCCCCTCACTC...,AATAGCTCAGAATGTCAGTTCTG,hsa-miR-7705,unknown,three_prime_utr,0,1,11054610,11054659,-,0,UTR3,UTR3,5366.0,5415.0,4086,"[1.636, 3.556, 1.108, 0.415, 2.519, 0.028, 1.7...","[1.0, 1.0, 1.0, 0.997, 0.995, 0.422, 0.426, 0...."
2,GCCTCATGCGCTCACGGGTTCGGGGGGCCGATGCTGCCCAAGCCAA...,AGAATTCTCTTATCCAACATCAACA,hsa-miR-10393-5p,unknown,exon,0,1,230243306,230243355,+,0,CDS,CDS,176098.0,176147.0,1133,"[9.982, -0.142, 0.638, 8.001, 3.424, 9.306, 8....","[1.0, 0.329, 0.425, 1.0, 1.0, 1.0, 1.0, 1.0, 1..."
3,AAGAAAATGGTTCAAGGGCATGGGGGTTAGAGAATGTTTCTTTTAC...,GCTAAGGAAGTCCTGTGCTCAG,hsa-miR-4521,unknown,three_prime_utr,0,1,15667922,15667971,+,0,UTR3,UTR3,50423.0,50472.0,936,"[1.805, 1.184, -0.033, 0.308, 0.686, 0.375, 0....","[0.019, 0.017, 0.003, 0.002, 0.003, 0.002, 0.0..."
4,CCACCTGCAACCCCAATCTCAATCCGGAGGCCAGTAGCACCAGGAT...,TGAAGCGCCTGTGCTCTGCCGAGA,hsa-miR-7706,unknown,exon,0,1,155675013,155675062,-,0,UTR3,UTR3,13912.0,13961.0,1488,"[2.34, 3.012, 4.205, 0.492, 4.243, 0.419, 0.81...","[1.0, 1.0, 1.0, 1.0, 1.0, 0.975, 0.963, 0.951,..."

In [7]:
import pandas as pd
from miRBench.dataset import get_dataset_path

# 1. Load the first dataset using Pandas and view the first 5 lines
print("--- AGO2_CLASH_Hejret2023 Dataset ---")
path1 = get_dataset_path('AGO2_CLASH_Hejret2023', split="test")
df1 = pd.read_csv(path1, sep='\t')
display(df1.head())

# 2. Load the second dataset using Pandas and view the first 5 lines
print("\n--- AGO2_eCLIP_Klimentova2022 Dataset ---")
path2 = get_dataset_path('AGO2_eCLIP_Klimentova2022', split="test")
df2 = pd.read_csv(path2, sep='\t')
display(df2.head())

--- AGO2_CLASH_Hejret2023 Dataset ---
Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_CLASH_Hejret2023\test\dataset.tsv

,gene,noncodingRNA,noncodingRNA_name,noncodingRNA_fam,feature,label,chr,start,end,strand,Nunique,dominant_region,regions_present,read_start_in_sel_tx_1based,read_end_in_sel_tx_1based,gene_cluster_ID,gene_phyloP,gene_phastCons
0,GGAGTCTGGAGTCAAACCCAGAGCAGCTGCAGGCCATGAGGCACAT...,AAAGCAAATGTTGGGTGAACGGC,hsa-miR-10527-5p,unknown,exon,0,1,112694760,112694809,+,0,CDS,CDS,20016.0,20065.0,834,"[2.923, 0.02, 2.412, 1.039, 0.48, 2.867, 7.669...","[1.0, 0.943, 0.99, 0.99, 0.99, 1.0, 1.0, 1.0, ..."
1,CAGCTGTGTACAGCGCCATCTCTCTGCCTTCTGTTGCCCCTCACTC...,AATAGCTCAGAATGTCAGTTCTG,hsa-miR-7705,unknown,three_prime_utr,0,1,11054610,11054659,-,0,UTR3,UTR3,5366.0,5415.0,4086,"[1.636, 3.556, 1.108, 0.415, 2.519, 0.028, 1.7...","[1.0, 1.0, 1.0, 0.997, 0.995, 0.422, 0.426, 0...."
2,GCCTCATGCGCTCACGGGTTCGGGGGGCCGATGCTGCCCAAGCCAA...,AGAATTCTCTTATCCAACATCAACA,hsa-miR-10393-5p,unknown,exon,0,1,230243306,230243355,+,0,CDS,CDS,176098.0,176147.0,1133,"[9.982, -0.142, 0.638, 8.001, 3.424, 9.306, 8....","[1.0, 0.329, 0.425, 1.0, 1.0, 1.0, 1.0, 1.0, 1..."
3,AAGAAAATGGTTCAAGGGCATGGGGGTTAGAGAATGTTTCTTTTAC...,GCTAAGGAAGTCCTGTGCTCAG,hsa-miR-4521,unknown,three_prime_utr,0,1,15667922,15667971,+,0,UTR3,UTR3,50423.0,50472.0,936,"[1.805, 1.184, -0.033, 0.308, 0.686, 0.375, 0....","[0.019, 0.017, 0.003, 0.002, 0.003, 0.002, 0.0..."
4,CCACCTGCAACCCCAATCTCAATCCGGAGGCCAGTAGCACCAGGAT...,TGAAGCGCCTGTGCTCTGCCGAGA,hsa-miR-7706,unknown,exon,0,1,155675013,155675062,-,0,UTR3,UTR3,13912.0,13961.0,1488,"[2.34, 3.012, 4.205, 0.492, 4.243, 0.419, 0.81...","[1.0, 1.0, 1.0, 1.0, 1.0, 0.975, 0.963, 0.951,..."

--- AGO2_eCLIP_Klimentova2022 Dataset ---
Downloading AGO2_eCLIP_Klimentova2022 dataset, split test into C:\Users\05vic\.miRBench\datasets\20540907\AGO2_eCLIP_Klimentova2022\test\dataset.tsv

,gene,noncodingRNA,noncodingRNA_name,noncodingRNA_fam,feature,label,chr,start,end,strand,Nunique,dominant_region,regions_present,read_start_in_sel_tx_1based,read_end_in_sel_tx_1based,gene_cluster_ID,gene_phyloP,gene_phastCons
0,GCTAACAACATCTGCACAGCACCTTACAGTTTGCAAAGAACGTTCA...,TAAGGTGCATCTAGTGCAGATAG,hsa-miR-18a-5p,mir-17,three_prime_utr,1,X,151408978,151409027,+,56,UTR3,UTR3,11775.0,11824.0,120,"[2.374, 2.999, 1.741, 1.943, 1.913, 1.502, 0.3...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.999, 1.0, 1.0..."
1,TCTTCCTTTTCCCCACGTTCAGTGTAATCTCACTGAACAGTAATAA...,TAAGGTGCATCTAGTGCAGATAG,hsa-miR-18a-5p,mir-17,three_prime_utr,1,X,151408924,151408973,+,10,UTR3,UTR3,11721.0,11770.0,429,"[1.035, 1.013, 3.067, 3.067, 3.03, 1.714, 1.69...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.992..."
2,ACAGAGCCATATGTACCCTACCCTGCACATTGTTATGCACTTTTCC...,AAAAGTGCTTACAGTGCAGGTAG,hsa-miR-106a-5p|hsa-miR-17-5p|hsa-miR-20a-5p,mir-17,three_prime_utr,1,6,29602598,29602647,-,6,UTR3,UTR3,25406.0,25455.0,424,"[-1.505, -0.288, -0.002, 0.472, 0.491, 0.404, ...","[0.0, 0.0, 0.0, 0.001, 0.001, 0.001, 0.0, 0.0,..."
3,CACTCCATCAGCACTAGCACCTCACTCCATCGGCCCCGGCACCCTG...,TAAGGTGCATCTAGTGCAGATAG,hsa-miR-18a-5p,mir-17,three_prime_utr,1,16,3142151,3142200,+,6,UTR3,UTR3,7124.0,7173.0,123,"[-1.539, -1.071, 0.108, -0.189, 1.403, 0.263, ...","[0.0, 0.0, 0.001, 0.01, 0.01, 0.005, 0.001, 0...."
4,GTAAGCACTTTATCTCCAGAACTGAGAGCAAAGTTAACAAATCTCA...,TAAAGTGCTTATAGTGCAGGTAG,hsa-miR-20a-5p|hsa-miR-17-5p,mir-17,intron,1,20,49246738,49246787,-,5,UTR3,UTR3,31279.0,31328.0,421,"[0.724, 2.218, 0.344, 0.326, 0.321, 0.91, 1.77...","[0.117, 0.385, 0.371, 0.368, 0.377, 0.417, 0.4..."